---
printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: 'all'
bracketSpacing: true
arrowParens: 'always'
# plugins:
  # - '@prettier/plugin-ruby'
overrides:
  - files: '*.rb'
    options:
      parser: ruby
  - files: '*.ts'
    options:
      parser: typescript
  - files: '*.json'
    options:
      parser: json
